// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./name')
const sayHi = require('./utils')
const data = require('./alternative')
require('./07-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)